# Generated by Django 3.1.2 on 2021-06-09 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
